### PR TITLE
REC version of document(s)

### PR DESCRIPTION
**Pull request by mcdittmar**
Note: there is an open issue? with the schema file (.xsd) which imports vodml-base.xsd which currently only resides in the git repository.  This is not a lien on the document release.

### CODE REVIEW

**Review by lmichel — CHANGES_REQUESTED** [review]
The http://volute.g-vo.org/svn/trunk/projects/dm/vo-dml/models/ivoa/vo-dml/IVOA-v1.0.html URL in the HTML are not working. They should be replaced with the ivoadocURL

**Comment by mcdittmar** [comment]
> 

Are you referring to the links for the specific attributes? (eg: Axis.name == ivoa::string type?)
I know those links do not currently work, but I thought we discussed that:
* A conservative approach is to use a link on the VODML landing page which enclose the IVOA sub-model definitions.

which is what those links represent.
Are you saying you'd like each of the IVOA model links to go to the VODML landing page (with no \#element)?

**Comment by lmichel** [comment]
You must no longer have any volute URLs. 
I didn' notice you need URLs pointing on specific label such as http://volute.g-vo.org/svn/trunk/projects/dm/vo-dml/models/ivoa/vo-dml/IVOA-v1.0.html#integer and that you need this file to be online, which is not the case.
2 options: 
- asking the doc coordinator to add both  IVOA-v1.0.html and vodml-v1.0.html on the VODML landing page.
- using the github URL.

The first is safer but takes a little time.

**Comment by mcdittmar** [comment]
> You must no longer have any volute URLs. I didn' notice you need URLs pointing on specific label such as http://volute.g-vo.org/svn/trunk/projects/dm/vo-dml/models/ivoa/vo-dml/IVOA-v1.0.html#integer and that you need this file to be online, which is not the case. 2 options:
> 
> * asking the doc coordinator to add both  IVOA-v1.0.html and vodml-v1.0.html on the VODML landing page.
> * using the github URL.
> 
> The first is safer but takes a little time.

I'm confused, the only volute links in the new documents are the style sheets.  The IVOA-v1 links are all using the ivoa.net location where the HTML file would be if we went with option 1 (modulo the minor version).

My thinking was that we could push these, with the links broken, until the underlying files got installed per option 1.

**Comment by lmichel** [comment]
I'm sorry something happened with my browser (or with me) 
HTML seams to be right now

**Review by lmichel — DISMISSED** [review]

**Review by lmichel — APPROVED** [review]

**Pull request merged**
